[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/p/*"
  to = "/v151/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
